#ifndef OPENBMC_KVM_PROTOCOL_H
#define OPENBMC_KVM_PROTOCOL_H

#include <stdint.h>

#define KVM_FRAME_MAGIC0 0xA5u
#define KVM_FRAME_MAGIC1 0x5Au
#define KVM_PROTOCOL_VERSION 0x01u

#define KVM_PACKET_KEYBOARD 0x01u
#define KVM_PACKET_POINTER 0x02u
#define KVM_PACKET_HEARTBEAT 0x03u
#define KVM_PACKET_RELEASE_ALL 0x04u

#define KVM_KEYBOARD_REPORT_SIZE 8u
#define KVM_POINTER_REPORT_SIZE 6u
#define KVM_MAX_PAYLOAD_SIZE KVM_KEYBOARD_REPORT_SIZE

#define KVM_UART_BAUDRATE 921600u
#define KVM_LINK_TIMEOUT_MS 1000u

#endif
